version: 2

sources:
    - name: raw_to_stg
      database: zoomcamp-380308
      schema: carbon

      # loaded_at_field: record_loaded_at
      tables:
        - name: emissions
        - name: codes